# -*- coding: utf-8 -*-
"""Sistema de Conversão de PDF para DOCX em Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15P2nUGpGaqgcT3Cqr5UWMi76twCEiDMh
"""

# Instalar biblioteca
!pip install pdf2docx

# Importar biblioteca
import os
from pdf2docx import Converter
from google.colab import files
from datetime import datetime

# Criar pasta de saída
output_dir = "convertidos"

if not os.path.exists(output_dir):
    os.makedirs(output_dir)

print("Pasta criada com sucesso.")

# Fazer upload do PDF | Upload de múltiplos PDFs
from google.colab import files

uploaded = files.upload()

# Função de conversão
def converter_pdf_para_docx(pdf_file, pasta_saida):
    try:
        nome_base = os.path.splitext(pdf_file)[0]
        docx_file = os.path.join(pasta_saida, f"{nome_base}.docx")

        cv = Converter(pdf_file)
        cv.convert(docx_file)
        cv.close()

        print(f"✔ Convertido: {pdf_file}")
        return docx_file

    except Exception as e:
        print(f"❌ Erro ao converter {pdf_file}: {e}")
        return None

# Converter todos os arquivos enviados
arquivos_convertidos = []

for arquivo in uploaded.keys():
    resultado = converter_pdf_para_docx(arquivo, output_dir)
    if resultado:
        arquivos_convertidos.append(resultado)

print("\nProcesso finalizado.")

# Download automático
for arquivo in arquivos_convertidos:
    files.download(arquivo)